import BannerSection from "@/components/home/BannerSection";
import YourPartnerSection from "@/components/home/YourPartnerSection";
import ChooseUsSection from "@/components/home/ChooseUsSection";
import OurPartner from "@/components/home/OurPartner";
import HappyClientsSection from "@/components/home/HappyClientsSection";
import FAQ from "@/components/home/FAQ";
import BlogSection from "@/components/home/BlogSection";
import GetInTouch from "@/components/home/GetInTouch";
import AboutUs from "@/components/home/AboutUs";
import Meta from "@/components/shared/Meta";

export default function Home() {
  return (
    <>
      <Meta title="RiskIQ" content="Generated by create next app" />
      <BannerSection
        title={
          <>
            Technology Based Online <br /> Insurance Solutions Provider
          </>
        }
      />
      <AboutUs
        style={{ marginTop: "250px" }}
        title="ABOUT US"
        subTitle="RiskIQ Insurance"
        btnText="READ MORE"
      />
      <YourPartnerSection
        title={
          <>
            Your Partner in Insurance
            <br /> Business Growth.
          </>
        }
        para="Lorem ipsum dolor sit amet consectetur. At odio elementum ac ut vel pellentesque eget. Risus nulla nunc commodo laoreet mattis ut viverra nunc non. Ullamcorper eget ipsum in mauris orci morbi. Vel diam sed eu pretium viverra elementum."
      />
      <ChooseUsSection title="WHY CHOOSE US ?" />
      <OurPartner
        title={
          <>
            Our <span>Partners</span>
          </>
        }
        para="Eget lacinia vulputate diam tempor. Porttitor consequat mattis nunc tellus in quisque rhoncus accumsan. Sit pellentesque ut estid nunc amet convallis. Dui odio quis arcu leo at turpis."
      />
      <HappyClientsSection
      />
      <FAQ title="FREQUENTLY ASKED QUESTIONS" />
      <BlogSection
        title={
          <>
            Our <span>Blog</span>
          </>
        }
        para="Eget lacinia vulputate diam tempor. Porttitor consequat mattis nunc tellus in quisque rhoncus accumsan. Sit pellentesque ut est id nunc amet convallis. Dui odio quis arcu leo at turpis."
      />
      <GetInTouch />
    </>
  );
}
